[package]
name = "crussmap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
log = "0.4.17"
log4rs = "1.2.0"
nom = "7.1.3"
rust-lapper = "1.1.0"
